name: Build and Release

on:
  push:
    tags:
      - 'v*'  # e.g. v1.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow cairosvg PyQt5

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller icomaker.py --noconfirm --onefile --windowed --icon=assets/app_icon_16×16.ico

      - name: Upload EXE as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: icomaker-windows
          path: dist/icomaker.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: icomaker-windows
          path: dist

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/icomaker.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
